# -*- coding: utf-8 -*-
"""check_gpu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDLs0qvY17D8-_4Ds5NDslVvl1oC_i5K

# Check the detail about GPU Hardware Accelator in Colab
"""

import tensorflow as tf
from tensorflow.python.client import device_lib

tf.test.gpu_device_name()

device_lib.list_local_devices()

