# -*- coding: utf-8 -*-
"""kaggle_data_download.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-bSWzsTCU18243Z75sY2zvs5q6uFbw6v

# Directly Upload Data from Kaggle

**Install Kaggle Package**
"""

!pip install -q kaggle

from google.colab import files

files.upload()

!mkdir ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list

!kaggle competitions download -c competitive-data-science-predict-future-sales